export {default as Home} from './home'
export {default as About} from './about'
export {default as Contact} from './contact'
export {default as Ditails} from './ditails'
export {default as Topic} from './topic'